# Alternative deployment option using App Engine
runtime: nodejs18

env_variables:
  NODE_ENV: production

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Health check configuration
health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60

# Resource configuration
resources:
  cpu: 1
  memory_gb: 0.5

handlers:
  - url: /static
    static_dir: dist/assets
    secure: always

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always